#Sonata
sonata_block:
    default_contexts: [cms]
    blocks:
         # enable the SonataAdminBundle block
         sonata.admin.block.admin_list:
             contexts: [admin]
         sonata.user.block.menu:    # used to display the menu in profile pages
         sonata.user.block.account: # used to display menu option (login option)
         sonata.block.service.text: # used to if you plan to use Sonata user routes

sonata_user:
    security_acl: false
    manager_type: orm # can be orm or mongodb

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    FOSUserBundle: ~ 
                    ApplicationSonataUserBundle: ~
                    ApplicationSonataMediaBundle: ~
                    ApplicationSonataClassificationBundle: ~
                    SonataUserBundle: ~
                    SonataMediaBundle: ~
                    SonataClassificationBundle: ~

sonata_media:
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: 1 # you need to set a context
    class:
        category: Application\Sonata\ClassificationBundle\Entity\Category
    contexts:
        1:  # the default context is mandatory
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        sonata_collection:
            providers:
              - sonata.media.provider.image
            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}
        sonata_category:
            providers:
              - sonata.media.provider.image
            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/
    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create: false

sonata_classification:
    class:
        #tag:      Application\Sonata\ClassificationBundle\Entity\Tag
        #category:      Application\Sonata\ClassificationBundle\Entity\Category
        #collection:      Application\Sonata\ClassificationBundle\Entity\Collection
        #media:        Application\Sonata\MediaBundle\Entity\Media
        #context:      Application\Sonata\ClassificationBundle\Entity\Collection
    #admin:
        #category:
            #class:        Sonata\ClassificationBundle\Admin\CategoryAdmin
            #controller:   SonataClassificationBundle:CategoryAdminController
            #translation:  SonataClassificationBundle